# .kodiak.toml
version = 1

[merge]
method = "rebase_fast_forward"

[approve]
# note: remove the "[bot]" suffix from GitHub Bot usernames.
# Instead of "dependabot[bot]" use "dependabot".
auto_approve_usernames = ["dependabot"]
