# .kodiak.toml
version = 1

[merge]
method = "rebase"

[update]
always = true
require_automerge_label = false

[approve]
# note: remove the "[bot]" suffix from GitHub Bot usernames.
# Instead of "dependabot[bot]" use "dependabot".
auto_approve_usernames = ["dependabot"]
