language: android
jdk:
  - oraclejdk8
android:
  components:
    - tools
    - build-tools-28.0.3
    # mtm
    - android-23
    - android-28
    - sysimg-28
    - extra-google-m2repository
    - extra-android-m2repository
  licenses:
    - android-sdk-license-.+
    - android-sdk-preview-license-.+

before_install:
  # Fix Gradle output
  - export TERM=dumb
  - yes | sdkmanager "platforms;android-28"

script:
  - ./gradlew --no-daemon check
