plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.plugin.compose'
}

dependencies {
    implementation rootProject
    implementation 'androidx.work:work-runtime:2.11.2'
    implementation 'androidx.appcompat:appcompat:1.7.1'

    implementation 'com.github.tony19:logback-android:3.0.0'

    // Compose
    def composeBom = platform('androidx.compose:compose-bom:2024.12.01')
    implementation composeBom
    implementation 'androidx.compose.material3:material3'
    implementation 'androidx.compose.ui:ui'
    implementation 'androidx.compose.ui:ui-tooling-preview'
    implementation 'androidx.activity:activity-compose:1.9.3'
    implementation 'androidx.lifecycle:lifecycle-viewmodel-compose:2.8.7'
    implementation 'androidx.browser:browser:1.8.0'
    debugImplementation 'androidx.compose.ui:ui-tooling'
}

def keystoreProperties = new Properties()
def keystorePropertiesFile = rootProject.file("keystore.properties")
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}

android {
    compileSdk 35
    defaultConfig {
        minSdkVersion 25
        targetSdkVersion 35
        versionCode 1430
        versionName "0.9.$versionCode"
        applicationId "org.bombusmod"
        namespace "$applicationId"
    }
    lintOptions {
        checkReleaseBuilds false
        abortOnError false
    }
    buildFeatures {
        compose = true
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    signingConfigs {
        release {
            keyAlias keystoreProperties['key.alias']
            keyPassword keystoreProperties['key.alias.password']
            storeFile keystoreProperties['key.store'] ? file(keystoreProperties['key.store']) : null
            storePassword keystoreProperties['key.store.password']
        }
    }
    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.release
        }
    }
}
