name: Gradle CI

on:
  pull_request:
  push:
    branches: [master]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v7
    - name: Set up JDK
      uses: actions/setup-java@v6
      with:
        distribution: 'temurin'
        java-version: '25'
        cache: 'gradle'
    - name: Setup Android SDK
      uses: android-actions/setup-android@v4
      with:
        packages: 'platform-tools'
    - name: Build
      run: ./gradlew -PenableIOS=true -PenableDesktop=true
