name: Gradle CI

on: 
  pull_request:
  push:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '18'
        cache: 'gradle'
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
    - name: Build
      run: ./gradlew -PenableIOS=true -PenableDesktop=true
